# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cn-wilsonshi\Desktop\work\scraping_image\appView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 308)
        self.search_label = QtWidgets.QLabel(Form)
        self.search_label.setGeometry(QtCore.QRect(60, 50, 91, 18))
        self.search_label.setObjectName("search_label")
        self.search_lineEdit = QtWidgets.QLineEdit(Form)
        self.search_lineEdit.setGeometry(QtCore.QRect(180, 50, 150, 21))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.page_label = QtWidgets.QLabel(Form)
        self.page_label.setGeometry(QtCore.QRect(60, 90, 72, 18))
        self.page_label.setObjectName("page_label")
        self.page_lineEdit = QtWidgets.QLineEdit(Form)
        self.page_lineEdit.setGeometry(QtCore.QRect(180, 90, 150, 21))
        self.page_lineEdit.setObjectName("page_lineEdit")
        self.filename_lineEdit = QtWidgets.QLineEdit(Form)
        self.filename_lineEdit.setGeometry(QtCore.QRect(180, 130, 150, 21))
        self.filename_lineEdit.setObjectName("filename_lineEdit")
        self.filename_label = QtWidgets.QLabel(Form)
        self.filename_label.setGeometry(QtCore.QRect(60, 130, 111, 18))
        self.filename_label.setObjectName("filename_label")
        self.link_pushButton = QtWidgets.QPushButton(Form)
        self.link_pushButton.setGeometry(QtCore.QRect(50, 190, 93, 28))
        self.link_pushButton.setObjectName("link_pushButton")
        self.google_pushButton = QtWidgets.QPushButton(Form)
        self.google_pushButton.setGeometry(QtCore.QRect(150, 190, 93, 28))
        self.google_pushButton.setObjectName("google_pushButton")
        self.baidu_pushButton = QtWidgets.QPushButton(Form)
        self.baidu_pushButton.setGeometry(QtCore.QRect(250, 190, 93, 28))
        self.baidu_pushButton.setObjectName("baidu_pushButton")
        self.zip_pushButton = QtWidgets.QPushButton(Form)
        self.zip_pushButton.setGeometry(QtCore.QRect(100, 240, 93, 28))
        self.zip_pushButton.setObjectName("zip_pushButton")
        self.count_pushButton = QtWidgets.QPushButton(Form)
        self.count_pushButton.setGeometry(QtCore.QRect(200, 240, 93, 28))
        self.count_pushButton.setObjectName("count_pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(380, 50, 211, 221))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "爬图 V 1.0.1"))
        self.search_label.setText(_translate("Form", "链接/关键词"))
        self.page_label.setText(_translate("Form", "页数"))
        self.filename_label.setText(_translate("Form", "文件名(仅链接)"))
        self.link_pushButton.setText(_translate("Form", "链接"))
        self.google_pushButton.setText(_translate("Form", "谷歌"))
        self.baidu_pushButton.setText(_translate("Form", "百度"))
        self.zip_pushButton.setText(_translate("Form", "压缩"))
        self.count_pushButton.setText(_translate("Form", "文件总合"))

        self.setWindowOpacity(0.9) # 设置窗口透明度
        # 美化风格
        self.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
